### ISSUE TITLE
Assigning a Media Source breaks TV

### ISSUE THREAD

**Issue by chunkyRice** [alanpich/tvImagePlus#11]
When I assign a Media Source (other than the default Filesystem) to an Image+ TV, it can no longer find my image. The TV will not display a thumbnail, nor does the editor display the image (or the UI). The TV will not be parsed and included in the rendered Resource.

The Media Source works fine in other TV's and in the Filebrowser.

**Comment by alanpich** [comment]
Fixed in v2.1
