### ISSUE TITLE
Button needs icon for cropping (scissors or so)

### ISSUE THREAD

**Issue by exside** [alanpich/tvImagePlus#16]
Title says it all =), in my just downloaded build v2.1 there is no icon show inside the button that opens the cropping window.

Is there one and just not shown on my side or could this be added?

**Comment by alanpich** [comment]
![crop-icon](https://f.cloud.github.com/assets/902992/495955/f87e24bc-bbd5-11e2-91cf-e2086d4aa1f1.png)
Moved icon here so I could close the other issue

**Comment by alanpich** [comment]
Added to develop branch ready for release v2.2
