### ISSUE TITLE
Cropping window badly positioned on smaller screens

### ISSUE THREAD

**Issue by exside** [alanpich/tvImagePlus#17]
I'm on a MacBook Air 11" and if I click the button to open the cropping window, it appears way too far down (even if there was enough space to show it fully) so I have to manually drag it up, seems like a fixed pixel distance from top instead of a percentage...can this be?

and btw.: thank you very much for that great piece of code you're sharing with us...small donation welcome somewhere?

**Comment by alanpich** [comment]
This is a particular bug-bear of mine with the entire modExt interface... it doesn't play well on small or touch screens... fingers crossed it gets sorted out in v3 (ie replaced)

I'm reluctant to override the native Ext modal positioning, but i'll have a play and see if it can be moved upwards a bit.

And donations are very much welcome, thanks =) I've put a paypal button up at http://alanpich.com

**Comment by exside** [comment]
bought you a beer (hopefully =D)! And yeah, the positioning of the modal sucks in many extras on small screens

**Comment by alanpich** [comment]
Yes indeed, many thanks! Just for that I'll let you pick the crop button icon I'll add in the next version

**Comment by exside** [comment]
=), thanks, how about this one? ![noun_project_92](https://f.cloud.github.com/assets/445501/217007/1a97b00c-84dd-11e2-862c-6b5d8a47ad71.png)
