### ISSUE TITLE
option to hide edit button

### ISSUE THREAD

**Issue by eighthday** [alanpich/tvImagePlus#19]
It would be great if the edit button was optional

**Comment by alanpich** [comment]
I'm disincined to include this request as it would be a very inefficient way of forcing image size. If you don't need the user to be able to control cropping areas then it would be less expensive in terms of processing time to use a regular Image TV and then use the phpthumbof output filter directly on the tag in the template.

**Comment by eighthday** [comment]
The problem is my clients do not get on with the modx filebrowser at all, so I really like the way tvImagePlus bypasses it.

**Comment by alanpich** [comment]
SimpleFileUpload may suit your needs better

http://modx.com/extras/package/simplefileuploadtv
