### ISSUE TITLE
Not working with Articles 

### ISSUE THREAD

**Issue by yuka123** [alanpich/tvImagePlus#21]
Getting this error:

this.tvimageplus.sourceImg.src is null 

also weird the console in firebug says:

"NetworkError: 404 Not Found - assets/components/tvimageplus/js/mgr/input/Ext.CropWindow.js?v=224pl"

Ext.Cr...v=224pl

"NetworkError: 404 Not Found - assets/components/tvimageplus/js/mgr/input/Ext.ux.crop.js?v=224pl"

Ext.ux...v=224pl

"NetworkError: 404 Not Found - assets/components/tvimageplus/js/mgr/input/Ext.cropwindow.ui.js?v=224pl"

Ext.cr...v=224pl

"NetworkError: 404 Not Found - assets/components/tvimageplus/js/mgr/input/tv.input.js?v=224pl"

tv.inp...v=224pl

"NetworkError: 404 Not Found - assets/components/tvimageplus/js/mgr/input/Ext.CropWindow.js?v=224pl"

Ext.Cr...v=224pl

"NetworkError: 404 Not Found - assets/components/tvimageplus/js/mgr/input/tv.input.js?v=224pl"

**Comment by alanpich** [comment]
Is your assets directory installed somewhere other than `[[site_path]]assets/` ?

**Comment by yuka123** [comment]
No it shouldn't be so. Could you test if it's working for your on newest Articles extra!

**Comment by Monady** [comment]
as i have seen, it doesn't work when you have the resource in a container. if is in a root it works fine.

**Comment by Monady** [comment]
also, the path /tvimageplus/js/mgr/ doesn;t exist in the install.
