### ISSUE TITLE
Add option to reset tv to empty value

### ISSUE THREAD

**Issue by alanpich** [alanpich/tvImagePlus#22]

**Comment by alanpich** [comment]
All TVs can be cleared using the little green icon to the right of the TV name.
It is hidden until you mouse over the TV's name label - looks like this 
![modx-resettv-icon](https://f.cloud.github.com/assets/902992/508858/39f1acde-bd93-11e2-8ab2-f03bc15eff63.png)

**Comment by Glidias** [comment]
oh my,  i didn't know MODx had that. lol. But I added a 'Clear Image' button in my fork: https://github.com/Glidias/tvImagePlus/commit/9d1b9391fa5029d656586aeb6bf48219e1f94cdb
Oh well, at least end users can easily SEE the button, if they have trouble rolling over to find the icon....
