### ISSUE TITLE
Thumbs filled to specified dimmensions even if source image is smaller than crop area

### ISSUE THREAD

**Issue by lithiumlab** [alanpich/tvImagePlus#34]
Let say we have a source image 300x500 on a imageplus configured to 460x160.
The current functionality does not allows the handles to be reduced to the width of 300. It would be very helpful if handles are adjusted to the width of the smaller source file even if the thumb generated is going to be poor quality so the general aspect of the layout doesn't suffer.

**Comment by alanpich** [comment]
Closed for combination into #56
