### ISSUE TITLE
Completely not working. Lots of Issues

### ISSUE THREAD

**Issue by Glidias** [alanpich/tvImagePlus#36]
1) Custom media source doesn't work and always browse start from root FileSystem location rather than Media source folder location. As a result, PHPThumb cannot retrieve the image correctly from media source due to double appending a full URL path from Filesystem root rather than having a path relative to the media source.

2) Even if I use Root Filesystem, the PHPThumb may show correctly, but when i try to sample a region, I get a full-black image or images with black spots even though the sampled region is within the bounds of the image! Is negative coordinates expected?

3) UI is lacking proper features. Why can;t you set predefined sizes (content-managed width and height ratio schemes to choose from given a specific template variable), and simply drag such the region box around and size it proportionately to capture any part of an image? You should clamp the region box to the image bounds as well, or give some UI warning message to state that the region box is outside image bounds (and a selectable background color will be used instead).  Manually dragging the bounding box's edges isn't intuitive (it doesn't even give numeric pixel values or number entry input-fields) and is pretty much useless for REAL-Life situations where more often than not, predefined sizes are needed and the client only needs to capture a certain part of an image given that predefined size ratio. For example, Wordpress does such things well as far as  uploading and sampling portions of an image is concerned, providing the necessary graphical UI to manage image outputs online from a given image source.

Another thing, why have a plugin like ImageTV+ when such a feature should have been part of the MODx core (Image template variable) itself to begin with. MODx is lacking a lot of features as far as proper Image management is concerned, one that you'd expect from any given CMS.

I'm not sure if output filter allows you to fish out the target output width/height of the image as well. That way, templating can be done to output <img width="" height=""> even if the image isn't loaded yet, which is good for load-independant metrics.

**Comment by alanpich** [comment]
I'll check up on the media source issue if you can post exact steps to reproduce the issue (media source setup etc).

As for the third point you made, perhaps the documentation available on **[RTFM](http://rtfm.modx.com/pages/viewpage.action?pageId=43417765)** might address some of your issues. Specifically, **[RTFM](http://rtfm.modx.com/pages/viewpage.action?pageId=43417765)** will demonstrate how to "set pre-defined sizes for a specific template variable" which will in turn "clamp the region box to the image bounds as well". **[RTFM](http://rtfm.modx.com/pages/viewpage.action?pageId=43417765)** also describes how to "fish out the target output width/height" using a chunk for output.

I don't work for Modx, so I have not been involved in previous versions. There is talk of integrating Image+ features into the core for the next release but hasn't yet been confirmed.

I'm happy to help out if you are having difficulties implementing my free, open-source components, but before positing that they are flawed and completely unusable, please PLEASE **[RTFM](http://rtfm.modx.com/pages/viewpage.action?pageId=43417765)**

**Comment by Glidias** [comment]
Regarding 1), it's the same issue as https://github.com/alanpich/tvImagePlus/issues/33 . 
For 3) , it's working now so long as both width and height is specified.

**Comment by Glidias** [comment]
Regarding 2), I made some changes. 

```
   // If server returns something higher than 800x600, image may be larger
    //  so need to get size manually

    if(img.image_width >= 800 || img.image_height >= 600){
        this.manual_getImageSize();
    } else {        
        // Update display
        this.updateDisplay();
    };
```

Previously, it was like 

```
if (img.image_width == 800 && img.image_height == 600){
        this.manual_getImageSize();
    } else {     
 // Update display
        this.updateDisplay();
 }
```

I was using a 890x490px source image in such a case, and it resulted in capped image of like 800x460px (not sure about the height, i think it changed proportionately to fit the window size of 800x600.), resulting in the crop rectangle height exceeding the preview image. I'd rather stick to the source image size as always so I asserted getting the exact image size manually for the preview image. I noticed when the crop rectangle exceeds for the earlier case, it causes negative sx/sy values for the PHPThumb, thus causing black regions to be displayed. I'm not sure exactly what's the window-size cap limit of 800x600 for, but chances are, the source will rarely land exactly at 800x600 pixels. 

Is it because crop rectangle needs to be also adjusted to the displayRatio (for scaled down images in the window...), but it doesn't?? Anyway, i decided to keep things simply by ensuring displayRatio to be 1, but this might be a problem for larger images where the Editor preview may still need a scaled down version to avoid the Editor window from getting too big.  Maybe the Editor window could use an overflow:auto approach.

**Comment by Glidias** [comment]
For 1), under imageplus.panel.input.js, i think you assigned the "source" option wrongly when initing the MODx file browser, using this.tvimageplus.sourceImg.source, when it's obvious because sourceImg settings are only set upon "on_imageSelected" (so for first time users of the TV that hasn't selected an image yet, he won't get the correct media source path!) .

So, here's the fix for the source line:

```
 ,create_imageBrowser: function(){
    // Generate opento path
    var openToPath = this.tvimageplus.sourceImg.src.split('/');
        openToPath.pop();
        openToPath = openToPath.join('/');
    // Create browser component
    this.imageBrowser = new MODx.combo.Browser({
        value: this.tvimageplus.sourceImg.src
        ,source: this.tvimageplus.mediaSource
        ,openTo: openToPath
        ,listeners: {
            'select': {fn: this.on_imageSelected,scope:this}
        }
    })
}
```

When previously, it was  

```
    ,source: this.tvimageplus.sourceImg.source
```

I find it confusing....why have 2 duplicate variable values like "this.tvimageplus.mediaSource" and another which is "this.tvimageplus.sourceImg.source"? Why not stick to the same thing (ie. the earllier one)?  Unless of course, i think you might be passing sourceImg as a parameter to another function from a different js file, so you need the duplicate variable reference just to hold that extra info..?

Anyway, i got it to work, even though I'm considering of trying to improve it by having a default crop rectangle be pre-emptively checked (and made optionally available) after the image gets selected (without having to click on Edit Image to trigger it), thus allowing the defered updatePreviewImage() function to execute and display a default starting preview image immediately without having to click on Edit Image . However, this may/may not be a good feature to include though, as it adds unnecessary bandwidth assuming the user is going to click on Edit Image most of the time anyway. Currently, I'm doing a check where if the crop.width or corp.height is zero after an image gets selected, to open up the Editor automatically for the user. Also, if the image selected is different from the previous one, i reset the crop rectangle to the default settings of (x=0, y=0, width=config.targetWidth, height=config.targetHeight).

For 2) i think black regions and black preview thumbnails occur when the crop rectangle exceeds outside the bounds of the given image in the window. Of course, black regions are to be expected due to the background showing in such cases. However, the thumbnails and output images don't show correctly and often end up being fully black and all (the phpthumb urls end up with very large negative sx/sy values, which may be calculated wrongly considering the image doesn't output with the expeced black borders anyway). I think the interface could be improved by maybe having some canvas padding space in order to view any possible bleed out of the image. Or perhaps, the crop rectangle should be reduced down proportionately to fit the image window when it first opens (thus resulting in a smaller than normal crop rectangle)....and from there, will not be able to drag to exceed the image/window size. Of course, a smaller than normal crop rectangle means the image will be up-scaled (should give a warning in such a case), but this is not an normal case in most situations where clients should usually upload a big enough resolution image.

One cool feature that i think may be useful in some situations, is to allow to select from a range of pre-defined image sizes (rather than just 1 image size), and a row of buttons (or combo-box) to select the specific aspect ratio to use. But i guess, this could be a seperate plugin altogether in order to avoid feature creep.
