### ISSUE TITLE
No way of removing image reference from TV?

### ISSUE THREAD

**Issue by Glidias** [alanpich/tvImagePlus#37]
I tried to remove the text inside the input field, save, etc. but it has no effect and the image reference is still there. Is there a input/text change listener like in the regular Image TV?

Maybe the textfield could be made readonly, and include an additional button like Clear Image?

**Comment by yuka123** [comment]
Can confirm the issue. There is no other way then db to clear the image atm :S this is critical needs to be fixed asap.

**Comment by Glidias** [comment]
You can use the built-in MODx reset TV icon rollover thingy.  https://github.com/alanpich/tvImagePlus/issues/22

But I have a forked update as found in the above issue which includes a conspicuous "Clear Image" button.

**Comment by yuka123** [comment]
The reload modx icon doesen't work for me..Maybe on the new git 2.2.0 beta it does haven't rlly tested tbh.

**Comment by alanpich** [comment]
Merged from Glidias/tvImagePlus 582d6f4187993466cf062fc7c309dd3b2cabf3f7 . Nice touch, thanks!
