### ISSUE TITLE
"Image too Small" popup window mistakenly triggers for image TVs with Input Dimensions of >800 width or >600 height.

### ISSUE THREAD

**Issue by Glidias** [alanpich/tvImagePlus#40]
Your code has some image size capping at 800 x 600, thus causing loaded images whose size exceeds 800/600 to mistakenly be capped to 800x600, thus not fufilling the right dimensions/aspect ratio for higher Input Dimensions beyond the minimum Edit Image window size. Thus, it thinks the capped 800/600 image is smaller than the required (eg. 855x620 dimension) image.

As a result, I've altered the logic to support much larger images by replacing AND with OR and ==800/==600 with >=800 and >=600 respecitively, to always ensure   this.manual_getImageSize() is used for such cases.

https://github.com/Glidias/tvImagePlus/commit/9d1b9391fa5029d656586aeb6bf48219e1f94cdb

   if(img.image_width == 800 && img.image_height == 600){
vs
   if(img.image_width >= 800 || img.image_height >= 600){

I'm not sure if this is the "correct" way to go about it, though. But at least, it solves the problem for "Image Too Small" temporarily, allowing the image to be loaded and edited.

**Comment by alanpich** [comment]
This has been resolved for a while on the develop branch. Restriction is caused by the MODx.Browser image selector
