### ISSUE TITLE
feature request - scale to crop area

### ISSUE THREAD

**Issue by eighthday** [alanpich/tvImagePlus#41]
Hi,

A really nice feature would be to have a little checkbox called "scale to crop area", when this is selected the source image is resized as close as possible to the crop area (without changing aspect ratio)

**Comment by alanpich** [comment]
As is auto-cropping the image if you don't manually select the area?

**Comment by eighthday** [comment]
The issue we have is clients upload very large images, so they end up only being able to crop a very small part of the image. To stop this happening you could have a button that scales the image down to the crop area (without change ratio), before you take your crop.

**Comment by alanpich** [comment]
I still don't quite follow you... If you mean what I think you do, then check out the develop branch (upcoming v2.2 release); I think that has the features you're after
