### ISSUE TITLE
Tagged release of last 2.X release

### ISSUE THREAD

**Issue by MokoJumbie** [alanpich/tvImagePlus#60]
I can't find a transport package for 2.2.1 anywhere. Since 3.x is not ready for production, could you please provide a release of the last of the 2.x releases?

I would prefer to wait until 3.0 gets ironed out as it looks nice, but I have a time sensitive project. Thanks!

**Comment by alanpich** [comment]
Last release from the modx repo was v2.1 http://modx.com/extras/package/imageplustvinput?version=50c4c4e2f2455470fd00003a

Will see if i have a more recent build kicking around, bear with me

**Comment by alanpich** [comment]
v2.2 was used on a couple of personal projects but never released publicly https://github.com/alanpich/tvImagePlus/releases/tag/v2.2.0-beta

**Comment by MokoJumbie** [comment]
Fantastic, thanks! The reason I was looking for it is because the changelog mentioned some MIGX fixes which I am hoping to address similar issues I have been experiencing.

I was having some issues installing 3.0 beta, Once I get through this bit of work I'll see if I can send a meaningful bug report.
