### ISSUE TITLE
TV layout issue

### ISSUE THREAD

**Issue by christianhanvey** [alanpich/tvImagePlus#7]
When you use more than one tv of image+ tv type, inputs are all being grouped under the first label.
Not sure if this is an issue with your tv type, or a modx core issue.

For an example see: 
http://cl.ly/image/3v220R3C1u3z

All three tv's in this screenshot are of image+ type

**Comment by alanpich** [comment]
Schoolboy error... renderTo IDs weren't unique... fixed now
