### ISSUE TITLE
Thumbnail cropping

### ISSUE THREAD

**Issue by christianhanvey** [alanpich/tvImagePlus#8]
I'm not getting the correct cropped area after using the 'edit image' feature in the tv.
I've attached screenshot to demonstrate. It shows, from left: 
1 - output on the resource, 
2 - thumbnail for tv, 
3 - actual desired crop area

http://cl.ly/image/3Z3i1F1q2F2X

Tried this with several images, and all seem to crop the wrong area?

**Comment by mike85** [comment]
The same issue here. 

It just works on smaller images. When I try it with larger images like for example 1500x2000px then I get the wrong cropped area.

**Comment by alanpich** [comment]
That's odd... Did you set the target width/height on that tv or was it freeform?

**Comment by mike85** [comment]
I set the target size to 150x150px. The result image was the correct size however the wrong crop area.

**Comment by alanpich** [comment]
OK... seems to be an issue with the MODx File Browser... the cropper's dimensions are based on the height/width returned by this component (modx-combo-browser), but for large images if forces the size down to 800x600 :(

Will need to put in a custom preload size grabber to resolve this

**Comment by alanpich** [comment]
Added a manual image size grabber, havent got the opportunity to test on IE (dont know why it wouldnt work, but it feels like something IE would throw a fit over, could someone confirm this for me? )

**Comment by kudykam** [comment]
Is it solved? Because it still doesnt work for me... always different position of croped image. For images of all sizes...

**Comment by alanpich** [comment]
@kudykam What build commit are you working from? You can find the build commit ID in the readme via 'View Details' in the MODx package manager.

**Comment by kudykam** [comment]
Modx v 2.2.6, Image+ v 2.1. Actually it works for images with resolution 800x600 and lower. For higher res. cropping is inaccurate.

**Comment by alanpich** [comment]
In the package readme should be a git commit sha/id... Please post this so I can tell the exact version... I thought i'd fixed this already so need to know if bug still exists in latest release

**Comment by kudykam** [comment]
Date:     9th Dec 2012 5:01pm
Build:    e3a32ae27ea18fabded8a7aed49cc5ff27c7a554

**Comment by alanpich** [comment]
Works fine for images of 1280x and 1900x
